import React, { useState } from 'react';
import { 
  FileText, 
  Printer, 
  Download, 
  CheckCircle2, 
  Building2, 
  Leaf, 
  Flame, 
  Calendar, 
  AlertCircle,
  ShieldCheck,
  Trees
} from 'lucide-react';
import { CityData, WardZone, ReportItem } from '../types';
import { formatInterventionName } from '../services/scoringEngine';

interface ReportGeneratorProps {
  cities: CityData[];
  selectedCity: CityData | null;
  reportQueue: ReportItem[];
  onSelectCity: (city: CityData) => void;
  onClearQueue: () => void;
}

export const ReportGenerator: React.FC<ReportGeneratorProps> = ({
  cities,
  selectedCity,
  reportQueue,
  onSelectCity,
  onClearQueue,
}) => {
  const [cityId, setCityId] = useState<string>(selectedCity ? selectedCity.id : 'hyderabad');
  const [dateRange, setDateRange] = useState<string>('Q2_2026');
  const [isGenerated, setIsGenerated] = useState<boolean>(true);

  const activeCity = cities.find(c => c.id === cityId) || cities[0];

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    // Generate text/markdown export and trigger download
    const reportText = `
============================================================
HEAT2GREEN - URBAN HEAT & GREEN INFRASTRUCTURE REPORT
GOVERNMENT DECISION-SUPPORT PLANNING DOSSIER
============================================================
City: ${activeCity.name} (${activeCity.state})
Date: October 2026 | Ref: H2G/URBAN/REP/${activeCity.id.toUpperCase()}-2026
Generated by: Heat2Green Urban Environmental GIS Platform

1. EXECUTIVE SUMMARY
- Study Area: ${activeCity.totalAreaSqKm} sq. km
- Monitored Population: ${(activeCity.totalPopulation / 100000).toFixed(1)} Lakh
- Mean Daytime Land Surface Temperature: ${activeCity.avgLSTCelsius}°C
- Baseline Tree Canopy Cover: ${activeCity.avgGreenCoverPercent}% (Target: ≥25%)
- Identified Heat Hotspots: ${activeCity.totalHotspots} wards
- Critical Priority Zones: ${activeCity.criticalHotspots} wards
- Potential Land for Green Interventions: ${activeCity.potentialGreenHectares} hectares

2. MONITORED WARDS & RECOMMENDATIONS
${activeCity.wards.map((w, idx) => `
Ward ${idx + 1}: ${w.name} (${w.wardNumber})
- LST Temp: ${w.lstCelsius}°C | Heat Risk Score: ${w.heatRiskScore}/100
- Green Cover: ${w.greenCoverPercent}% | Built-up Surface: ${w.builtUpPercent}%
- Recommended Intervention: ${formatInterventionName(w.recommendedIntervention)}
- Tree Plantation Capacity: ~${w.estimatedTreeCapacity} native trees
- Projected Surface Cooling: -${w.potentialCoolingDelta}°C
- Action Reason: ${w.interventionReason}
`).join('\n')}

3. ENVIRONMENTAL & CARBON IMPACT PROJECTIONS
- Estimated Total Tree Capacity: ~${activeCity.wards.reduce((a, b) => a + b.estimatedTreeCapacity, 0)} trees
- Projected Annual Carbon Sequestration: ~${((activeCity.wards.reduce((a, b) => a + b.estimatedTreeCapacity, 0) * 21.8) / 1000).toFixed(1)} metric tonnes CO2/yr

Disclaimer: All values are computational planning estimates intended for municipal pre-feasibility analysis.
============================================================
    `.trim();

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Heat2Green_Plan_${activeCity.id}_2026.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Configuration Header Bar (no-print) */}
      <div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs no-print">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
          <div>
            <div className="flex items-center gap-2">
              <span className="p-1 rounded bg-[#EAF6EE] text-[#0B6B3A]">
                <FileText className="w-4 h-4" />
              </span>
              <h2 className="text-lg font-bold text-slate-900 font-serif">
                Municipal Urban Heat & Green Infrastructure Report Generator
              </h2>
            </div>
            <p className="text-xs text-slate-500 mt-0.5">
              Generate structured, verifiable planning dossiers aligned with state municipal development guidelines.
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-800 rounded-md text-xs font-semibold transition-colors"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print Report</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3.5 py-1.5 bg-[#0B6B3A] hover:bg-[#14532D] text-white rounded-md text-xs font-semibold shadow-xs transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download Dossier</span>
            </button>
          </div>
        </div>

        {/* Filter Controls */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-3 text-xs">
          <div>
            <label className="block text-slate-600 font-medium mb-1">Select Target City</label>
            <select
              value={cityId}
              onChange={(e) => {
                setCityId(e.target.value);
                const c = cities.find(city => city.id === e.target.value);
                if (c) onSelectCity(c);
              }}
              className="w-full bg-[#F5F8F6] border border-slate-300 rounded-md p-2 text-slate-800 font-medium focus:ring-1 focus:ring-[#0B6B3A]"
            >
              {cities.map(c => (
                <option key={c.id} value={c.id}>
                  {c.name} ({c.state})
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-slate-600 font-medium mb-1">Thermal Monitoring Cycle</label>
            <select
              value={dateRange}
              onChange={(e) => setDateRange(e.target.value)}
              className="w-full bg-[#F5F8F6] border border-slate-300 rounded-md p-2 text-slate-800 font-medium focus:ring-1 focus:ring-[#0B6B3A]"
            >
              <option value="Q2_2026">Pre-Monsoon Summer Peak (April – June 2026)</option>
              <option value="Q4_2026">Post-Monsoon Assessment (Oct – Dec 2026)</option>
              <option value="ANNUAL_2026">Consolidated Annual Baseline 2026</option>
            </select>
          </div>

          <div className="flex items-end">
            <button
              onClick={() => setIsGenerated(true)}
              className="w-full py-2 bg-[#12304A] hover:bg-[#0B5CAB] text-white rounded-md font-semibold text-xs transition-colors"
            >
              Refresh Report Synthesis
            </button>
          </div>
        </div>

        {reportQueue.length > 0 && (
          <div className="mt-3 p-2 bg-[#EAF6EE] rounded-lg border border-emerald-200 flex items-center justify-between text-xs">
            <span className="text-[#0B6B3A] font-medium">
              ★ {reportQueue.length} specific simulated ward scenario(s) queued for inclusion in this report.
            </span>
            <button
              onClick={onClearQueue}
              className="text-slate-500 hover:text-red-600 text-xs font-semibold"
            >
              Clear Queue
            </button>
          </div>
        )}
      </div>

      {/* Structured Official Report View (Print-ready document styling) */}
      <div className="bg-white border border-slate-300 rounded-xl p-8 shadow-sm space-y-6 max-w-4xl mx-auto print:border-none print:shadow-none print:p-0">
        {/* Document Header */}
        <div className="border-b-2 border-slate-900 pb-5">
          <div className="flex items-center justify-between">
            <div>
              <span className="text-[10px] font-mono-data uppercase font-bold text-slate-500 tracking-wider">
                URBAN HEAT & ENVIRONMENTAL ACTION REPORT
              </span>
              <h1 className="text-2xl font-bold text-slate-900 font-serif tracking-tight mt-0.5">
                HEAT2GREEN MUNICIPAL ACTION PLAN
              </h1>
              <p className="text-xs text-slate-600 font-medium">
                {activeCity.name} Metropolitan Region, State of {activeCity.state}
              </p>
            </div>
            <div className="text-right text-xs font-mono-data text-slate-500">
              <div>Ref: H2G/REP/{activeCity.id.toUpperCase()}/2026</div>
              <div>Date: October 02, 2026</div>
              <span className="inline-block px-2 py-0.5 mt-1 rounded bg-[#EAF6EE] text-[#0B6B3A] font-bold text-[10px] border border-[#2E7D32]/30">
                OFFICIAL GIS DOSSIER
              </span>
            </div>
          </div>
        </div>

        {/* Section 1: Executive Summary */}
        <section className="space-y-3">
          <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide border-l-3 border-[#0B6B3A] pl-2">
            1. Executive Summary
          </h3>
          <p className="text-xs text-slate-700 leading-relaxed">
            This technical document provides spatial thermal analysis and prioritized green infrastructure planning for <strong>{activeCity.name}</strong>. Satellite land surface temperature (LST) observations indicate a citywide mean daytime surface temperature of <strong>{activeCity.avgLSTCelsius}°C</strong>, with critical hotspot clusters reaching up to <strong>{Math.max(...activeCity.wards.map(w => w.lstCelsius))}°C</strong> in high-density industrial and commercial corridors.
          </p>

          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono-data text-xs">
            <div className="bg-slate-50 p-2.5 rounded border border-slate-200">
              <span className="text-[10px] text-slate-500 font-sans block">Study Area</span>
              <span className="text-sm font-bold text-slate-900">{activeCity.totalAreaSqKm} sq. km</span>
            </div>
            <div className="bg-slate-50 p-2.5 rounded border border-slate-200">
              <span className="text-[10px] text-slate-500 font-sans block">Canopy Cover</span>
              <span className="text-sm font-bold text-emerald-800">{activeCity.avgGreenCoverPercent}%</span>
            </div>
            <div className="bg-slate-50 p-2.5 rounded border border-slate-200">
              <span className="text-[10px] text-slate-500 font-sans block">Active Hotspots</span>
              <span className="text-sm font-bold text-red-600">{activeCity.totalHotspots} Wards</span>
            </div>
            <div className="bg-slate-50 p-2.5 rounded border border-slate-200">
              <span className="text-[10px] text-slate-500 font-sans block">Intervention Land</span>
              <span className="text-sm font-bold text-[#0B6B3A]">{activeCity.potentialGreenHectares} ha</span>
            </div>
          </div>
        </section>

        {/* Section 2: Hotspot & Ward Analysis Table */}
        <section className="space-y-3">
          <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide border-l-3 border-[#0B6B3A] pl-2">
            2. High Priority Hotspot Wards & Proposed Interventions
          </h3>
          <div className="overflow-x-auto border border-slate-200 rounded-lg">
            <table className="w-full text-xs text-left">
              <thead className="bg-[#F5F8F6] text-slate-700 font-semibold border-b border-slate-200 text-[10px] uppercase">
                <tr>
                  <th className="py-2 px-2.5">Ward / Zone</th>
                  <th className="py-2 px-2 text-right">LST</th>
                  <th className="py-2 px-2 text-right">Heat Risk</th>
                  <th className="py-2 px-2 text-right">Green Cover</th>
                  <th className="py-2 px-2.5">Recommended Intervention</th>
                  <th className="py-2 px-2 text-right">Tree Capacity</th>
                  <th className="py-2 px-2 text-right">Est. Cooling</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-mono-data">
                {activeCity.wards.map(ward => (
                  <tr key={ward.id}>
                    <td className="py-2 px-2.5 font-sans font-medium text-slate-800">
                      <div>{ward.name}</div>
                      <div className="text-[10px] text-slate-500">{ward.wardNumber} · {ward.district}</div>
                    </td>
                    <td className="py-2 px-2 text-right text-red-600 font-bold">{ward.lstCelsius}°C</td>
                    <td className="py-2 px-2 text-right font-bold text-amber-800">{ward.heatRiskScore}</td>
                    <td className="py-2 px-2 text-right text-emerald-800">{ward.greenCoverPercent}%</td>
                    <td className="py-2 px-2.5 font-sans text-slate-700">
                      <span className="font-semibold text-[#0B6B3A]">{formatInterventionName(ward.recommendedIntervention)}</span>
                    </td>
                    <td className="py-2 px-2 text-right">{ward.estimatedTreeCapacity.toLocaleString()}</td>
                    <td className="py-2 px-2 text-right text-emerald-700 font-bold">-{ward.potentialCoolingDelta}°C</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Section 3: Environmental & Carbon Sequestration Projections */}
        <section className="space-y-3">
          <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide border-l-3 border-[#0B6B3A] pl-2">
            3. Consolidated Environmental & Climate Benefits
          </h3>
          <p className="text-xs text-slate-700 leading-relaxed">
            Full deployment of prioritized interventions across the evaluated wards is projected to sequester approximately{' '}
            <strong className="text-[#0B6B3A]">
              {((activeCity.wards.reduce((a, b) => a + b.estimatedTreeCapacity, 0) * 21.8) / 1000).toFixed(1)} tonnes
            </strong>{' '}
            of atmospheric CO₂ annually upon tree maturity.
          </p>

          <div className="bg-[#EAF6EE] p-4 rounded-lg border border-emerald-200 text-xs text-slate-800 space-y-1">
            <div className="font-bold text-[#0B6B3A] uppercase tracking-wider text-[10px]">
              Statutory Carbon & Environmental Model
            </div>
            <div>
              • Recommended Native Canopy Species: Neem (Azadirachta indica), Peepal (Ficus religiosa), Jamun (Syzygium cumini), Pongamia (Millettia pinnata).
            </div>
            <div>
              • Microclimate Cooling Horizon: Expected surface temperature attenuation of 1.5°C to 3.2°C within 3–5 years of canopy establishment.
            </div>
          </div>
        </section>

        {/* Sign-off / Verification Seal Strip */}
        <div className="pt-6 border-t border-slate-200 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-500 gap-4">
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-5 h-5 text-[#0B6B3A]" />
            <div>
              <div className="font-semibold text-slate-800">Heat2Green Decision-Support Verification</div>
              <div className="text-[10px]">Computational GIS Engine · Version 2026.1</div>
            </div>
          </div>

          <div className="text-right text-[11px]">
            <div>Municipal Environmental Planning Section</div>
            <div className="font-mono-data text-slate-400">Timestamp: 2026-10-02 09:35 UTC</div>
          </div>
        </div>
      </div>
    </div>
  );
};
